# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python38"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python38-x64"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python39"
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python39-x64"
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python310"
      TOX_ENV: "py310"

    - PYTHON: "C:\\Python38-x64"
      TOX_ENV: "py310"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install -U poetry"
  - "poetry install"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "poetry run tox -e %TOX_ENV%"
